name: Delete Neon Branch

on:
  pull_request:
    types: [closed]

jobs:
  delete-branch:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Delete Neon Branch
      run: |
        curl -X DELETE https://console.neon.tech/api/v1/projects/${{ secrets.NEON_PROJECT_ID }}/branches/${{ github.head_ref }} \
        -H "Authorization: Bearer ${{ secrets.NEON_API_KEY }}"